server:
  port: 8080

spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/geek_db
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto=update: update

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.geekerstar.eastexcel.model

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
